### ISSUE TITLE
TypoScriptController not loaded

### ISSUE THREAD

**Issue by stadtkonzeptbasel** [einpraegsam/typoscript2ce#2]
after updating to 1.2.2 via TER i run into troubles under 7.6.15: 

`Could not analyse class: "In2code\Typoscript2ce\Controller\TypoScriptController" maybe not loaded or no autoloader? Class In2code\Typoscript2ce\Controller\TypoScriptController does not exist`

**Comment by einpraegsam** [comment]
Seems to me like a caching issue when the autoloader does not work.
Did you:
- Clean all caches in Install Tool (even OP-Caches)?
- Clean the typo3temp/* folder?
- If you are using composer, please do a "composer dump-autoload"

**Comment by stadtkonzeptbasel** [comment]
I've already tried that. i can reproduce it with a fresh 7.6 install without composer.
After a downgrade to 1.1.1 everything works again.

**Comment by Hobokens** [comment]
I have exactly the same problem with the same "solution".

**Comment by einpraegsam** [comment]
Thx for your notes. I fixed this in version 1.2.3 of the extension.

**Comment by stadtkonzeptbasel** [comment]
thank you for that fast fix!
