### ISSUE TITLE
TYPO3 9.5 compatibility

### ISSUE THREAD

**Issue by nebrot** [einpraegsam/typoscript2ce#3]
Are there any plans to make this extensions ready for TYPO3 9.5 LTS? We already tried it with current 9.5.1 and it's working for us without problems. So i think only version-changes in composer.json, ext_emconf.php, README.md and /Documentation/Main/Index.rst are needed.

**Comment by einpraegsam** [comment]
That is absolutely possible because this extension is a no brainer :)
Just do a PR and I will merge your changes.

**Comment by nebrot** [comment]
Thx, i'll try to create a PR

**Comment by nebrot** [comment]
PR in #4

**Comment by einpraegsam** [comment]
Thx, I just merged it :)

**Comment by nebrot** [comment]
Thx! Would be cool, if you can make a new release, when you've got some time :-)

**Comment by einpraegsam** [comment]
done 2.0.0 is availble now via composer and a few minutes later via TER
