### ISSUE TITLE
Possibility to change default template

### ISSUE THREAD

**Issue by icleikpe** [einpraegsam/typoscript2ce#8]
Hello,

I really like the typoscript extension and use it a lot. I would like to override the following: typo3conf/ext/typoscript2ce/Resources/Private/Layouts/Default.html. Is there a way of customising the layout template by defining a path to an own template in TYPO3 configuration like for Fluid.

The goal is to get rid of `<div class="tx-typoscript2ce">`.

Many thanks in advance.

**Comment by einpraegsam** [comment]
I did not test it, but in every extension, you can define your own template paths.
```
plugin.tx_extkey {
  view {
    templateRootPaths {
      10 = EXT:myextkey/Resources/Private/Templates/Extensions/Faq/
    }

    partialRootPaths {
      10 = EXT:myextkey/Resources/Private/Partials/Extensions/Faq/
    }

    layoutRootPaths {
      10 = EXT:myextkey/Resources/Private/Layout/Extensions/Faq/
    }
  }
}
```
BTW: Github is not a free support platform but only for bugs and missing features. Please ask at stackoverflow or slack next time :)
